Opening Post for Rome
RustFestEU/blog.rustfest.eu pull request #59
Opened 2018-08-22 07:35 UTC by tglman

2018-08-23 08:48 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to speak?** The [Call for Proposals](https://cfp.rustfest.eu/) is open! We would love to hear your proposal for a talk, workshop or discussion. Make sure to submit before **Date** As always, w
Maybe we should change this, if we are opening CFP later this week

2018-08-23 08:53 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to speak?** The [Call for Proposals](https://cfp.rustfest.eu/) is open! We would love to hear your proposal for a talk, workshop or discussion. Make sure to submit before **Date** As always, w
Maybe change also the post name to `2018-08-23-next-stop-rome.md`

2018-08-23 13:01 UTC, badboy requested changes

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +They say all the roads lead to Rome, so, after previous successful stops in Berlin, Київ, Zürich and Paris, it was just a matter of time before Rust Fest reached the Italian capital. We hope you'll j
Remove the comma after "so"

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +They say all the roads lead to Rome, so, after previous successful stops in Berlin, Київ, Zürich and Paris, it was just a matter of time before Rust Fest reached the Italian capital. We hope you'll j
```patch
- Rust Fest
+ RustFest
```

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +socialImageSrc: "/assets/posts/rome-panorama.jpg"
Where's the image coming from and what is its license?

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +![The Colosseum](assets/posts/rome.jpg)
Where's the image coming from and what is its license?

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +**What is Rustfest again?** It's a two day conference involving one day of workshops, and one day of talks! We aim for a diverse set of talks: technical and non-technical, advanced and beginner frien
Remove the comma before "and"

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +**What is it like?** Talks can be found online for [Berlin](https://www.youtube.com/watch?v=fI4RG_uq-WU&list=PL85XCvVPmGQh8nWR_Z-fTmPGsUWuzb-dn), [Київ](https://www.youtube.com/watch?v=AHprJNUCgQ0&li
cheese and bread, wine -> Pizza, Pasta & Espresso?

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to speak?** The [Call for Proposals](https://cfp.rustfest.eu/) is open! We would love to hear your proposal for a talk, workshop or discussion. Make sure to submit before **Date** As always, w
We definitely need to change this to make clear that the CfP opens soon.
yes about the file name change.

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +> Note this is a **hard deadline** this year, we will not be able to extend as timelines are already very tight. **Submit early**.
Let's remove this for now.

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to volunteer?** It's great to have a few locals who'd like to help attendees enjoy the experience. If you'd like to help guide a cohort of fellow hackers to your favorite restaurant, give dire
This link is not valid. 
Question is: do we take on official volunteers or do we only offer the space for discussion/planning around group activities?

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +> Note this is a **hard deadline** this year, we will not be able to extend as timelines are already very tight. **Submit early**.
Do we explicitely call out the CfP committee or do we save that for the CfP announcement?

2018-08-23 13:01 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +**Barriers to participating?** Not all of us can easily attend these events for a variety of reasons. We'll be working with [Diversity Tickets](https://diversitytickets.org/) again. If the ticket cos
Maybe link to the new "infos & policies" page as info for other barriers we try to handle?

2018-08-23 13:01 UTC, badboy commented on _data/team.yml
> +  nick: "tglman"
It's missing a picture for Emanuele.

2018-08-23 13:14 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +![The Colosseum](assets/posts/rome.jpg)
@badboy 
here it's the source
https://commons.wikimedia.org/wiki/File:Il_Colosseo_(261008409).jpeg

is it ok?

2018-08-23 13:16 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +socialImageSrc: "/assets/posts/rome-panorama.jpg"
@badboy 

here

https://commons.wikimedia.org/wiki/File:Rome_Skyline_(8012016319).jpg

2018-08-23 13:16 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +![The Colosseum](assets/posts/rome.jpg)
> This file is made available under the Creative Commons CC0 1.0 Universal Public Domain Dedication. 

All ok then!

2018-08-23 13:17 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +socialImageSrc: "/assets/posts/rome-panorama.jpg"
> This file is licensed under the Creative Commons Attribution-Share Alike 2.0 Generic license. 
> ...
> attribution – You must attribute the work in the manner specified by the author or licensor (but not in any way that suggests that they endorse you or your use of the work).

We need to name the author then, e.g. at the end of the post with a short note.

2018-08-23 13:20 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +**What is it like?** Talks can be found online for [Berlin](https://www.youtube.com/watch?v=fI4RG_uq-WU&list=PL85XCvVPmGQh8nWR_Z-fTmPGsUWuzb-dn), [Київ](https://www.youtube.com/watch?v=AHprJNUCgQ0&li
👍

2018-08-23 13:58 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to volunteer?** It's great to have a few locals who'd like to help attendees enjoy the experience. If you'd like to help guide a cohort of fellow hackers to your favorite restaurant, give dire
Not sure. Did we have official volunteers for Paris?

2018-08-23 14:07 UTC, badboy commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to volunteer?** It's great to have a few locals who'd like to help attendees enjoy the experience. If you'd like to help guide a cohort of fellow hackers to your favorite restaurant, give dire
Nope, only the team. We were so many that we didn't know what to do with more people :D

2018-08-23 20:42 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +socialImageSrc: "/assets/posts/rome-panorama.jpg"
This is the social image. i will remove this and use the other one.

2018-08-23 20:43 UTC, wolf4ood commented on _posts/2018-08-22-next-stop-rome.md
> +**Want to volunteer?** It's great to have a few locals who'd like to help attendees enjoy the experience. If you'd like to help guide a cohort of fellow hackers to your favorite restaurant, give dire
ok i will remove this content for now. I think we are also good for Rome

2018-08-23 21:34 UTC, apiraino approved these changes

2018-08-23 21:34 UTC, apiraino commented on _posts/2018-08-24-next-stop-rome.md
> +
`We prefer if team member ... `

2018-08-23 21:34 UTC, apiraino commented on _posts/2018-08-24-next-stop-rome.md
> +![The Colosseum](assets/posts/rome.jpg)
not sure but I think `/assets/posts/rome.jpg` (leading slash)

2018-08-24 10:06 UTC, badboy approved these changes

2018-08-24 10:06 UTC, merged